# 自定义层

### 1. 不带参数的层

In [302]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [303]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [304]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [305]:
Y = net(torch.rand([2,8]))
Y.mean()

tensor(-2.7940e-09, grad_fn=<MeanBackward0>)

### 2. 带参数的层

In [306]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn([in_units, units]))
        self.bias = nn.Parameter(torch.randn(units))
    def forward(self, X):
        linear = torch.matmul(X, self.weight) + self.bias
        return F.relu(linear)

In [307]:
linear = MyLinear(5, 3)
linear.bias

Parameter containing:
tensor([ 0.2245,  0.8858, -0.4953], requires_grad=True)

In [308]:
linear(torch.randn(2, 5))

tensor([[4.8538, 6.3052, 0.0000],
        [3.2312, 3.4887, 2.6002]], grad_fn=<ReluBackward0>)

In [314]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[15.4206],
        [15.3869]], grad_fn=<ReluBackward0>)